---
title: "Project Script"
author: "Laknath Dias Gunathilake"
date: "July 7, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Loading and Cleaning Data
```{r}
#Loading Required Library's
# Install these if they are not available 
library(here)
library(dplyr)
library(ggplot2)
```

```{r, Loading data}
#Loading the two datasets
# You should have a need to change the file path
df<-read.csv(here("datafiles","2006_-_2012_School_Demographics_and_Accountability_Snapshot.csv"))
df_results<-read.csv(here("datafiles","SAT__College_Board__2010_School_Level_Results.csv"))

```

```{r,combining data}
dftemp<-df%>%
  filter(schoolyear=="20102011")%>% # Obtaining  just the 2010 values
  distinct(DBN,.keep_all = T)  # This is to make sure that we keep only distinct                                   rows
df_demog<-dftemp # assigning df_temp to a temporary variable


df_results<-df_results%>%    # This gets rid of the rows where the Mathematics.mean
            filter(!is.na(Mathematics.Mean)) # is NA
  
df_cleaned<-left_join(df_results,df_demog,"DBN") # This combines using a left join 
                                                 # the cleaned results data and the                                                  # demographic dataset  


# The following code selects the required columns we want 
# in our datasetfor downstream ananalysis 
df_cleaned<-df_cleaned%>%
            select(DBN,
                   School.Name,
                   Number.of.Test.Takers,
                   total_enrollment,
                   Mathematics.Mean,
                   frl_percent,
                   total_enrollment,
                   ell_percent,
                   asian_per,
                   black_per,
                   white_per,
                   hispanic_per,
                   male_per,
                   female_per)

df_cleaned<-na.omit(df_cleaned) # This code removes rows that have any    
                                # NA values that are in the combined dataset                              
# This code saves the df_cleaned dataset into the datafiles folder
# You can now load this df_cleaned.csv dataset and continue on with the analysis

write.csv(df_cleaned,here("datafiles","df_cleaned.csv"))  
```



```{r}
## school type does not exist in this dataset

```

```{r, Laknath Code Section}
#https://nces.ed.gov/programs/coe/pdf/coe_clb.pdf
df_poverty<-df_cleaned%>%
  mutate(poverty=case_when(frl_percent>50~"mid to high poverty",
                              frl_percent<=50~"mid low to low poverty"))

poverty_low<-df_poverty%>%
              filter(poverty=="mid to high poverty")

hist(poverty_low$Mathematics.Mean)

poverty_high<-df_poverty%>%
  filter(poverty=="mid low to low poverty")

hist(poverty_high$Mathematics.Mean)

df_poverty<-df_poverty%>%
  filter(poverty %in% c("mid to high poverty","mid low to low poverty"))
  
povertyplot<-ggplot(data = df_poverty,aes(x = frl_percent,y = Mathematics.Mean))+
  geom_point(aes(color=poverty))+
  xlab("Percentage of students with free or reduced lunches")+
  ylab("Average SAT math score")+
  ggtitle("understanding relationship between poverty and SAT performance")

povertyplot

ggsave(filename = file.path(here("plots","povertyplot.png")))

t.test(`Mathematics.Mean` ~ poverty, data = df_poverty, var.equal = FALSE)

```
